services:
  - type: web
    name: smartbotchaskiq
    env: ruby
    plan: free
    buildCommand: |
      bundle install
      yarn install
      RAILS_ENV=production bundle exec rails assets:precompile
      RAILS_ENV=production bundle exec rails db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: chaskiq-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: chaskiq-redis
          type: redis
          property: connectionString
      - key: APP_DOMAIN
        value: https://smarbot-chasiq.onrender.com/
      - key: CHASKIQ_ADMIN_EMAIL
        value: crojas@iabot.com.co
      - key: CHASKIQ_ADMIN_PASSWORD
        value: IABOT2025*
      - key: RAILS_LOG_TO_STDOUT
        value: enabled

databases:
  - name: chaskiq-db
    databaseName: chaskiq_prod
    user: chaskiq_user

redis:
  - name: chaskiq-redis
